version: "1"
services:
  app:
    image: assignment4:latest3
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
      - "50051:50051"


  redis:
    image: redis:5.0.12
    command: redis-server --requirepass redispass
    ports:
      - 6379:6379


  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssw0rd!
      - POSTGRES_DB=Assignment4
    ports:
      - 5433:5433
    command: -p 5433